### ISSUE TITLE
Where is vendor_tools dir?

### ISSUE THREAD

**Issue by peerless2012** [Tencent/libpag#874]
Clone this project and open Android project with Android Studio, when run app and build so library, it has a error:

```
Execution failed for task ':libpag:configureCMakeDebug[arm64-v8a]'.
> [CXX1306] D:\Develop\Git\Demo\Image\libpag\CMakeLists.txt debug|arm64-v8a : CMake Error at D:\Develop\Git\Demo\Image\libpag\CMakeLists.txt:13 (include):
    include could not find load file:
    
    ./vendor_tools/vendor.cmake

```

Android Studio Flamingo | 2022.2.1
Build #AI-222.4459.24.2221.9862592, built on March 31, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins:
    name.kropp.intellij.makefile (222.4459.16)
    artsiomch.cmake (231.1.0)
    com.thoughtworks.gauge (222.4459.16)

**Comment by kevingpqi123** [comment]
From README：
Dependency Management
libpag uses depsync tool to manage third-party dependencies.

For macOS platform：

Just simply run the script in the root of libpag project:

./sync_deps.sh
This script will automatically install necessary tools and synchronize all third-party repositories.

For other platforms：

First, make sure you have installed the latest version of node.js (You may need to restart your computer after this step). And then run the following command to install depsync tool:

npm install -g depsync
And then run depsync in the root directory of libpag project.

depsync
Git account and password may be required during synchronizing. Please make sure you have enabled the git-credential-store so that CMakeList.txt can trigger synchronizing automatically next time.

**Comment by kevingpqi123** [comment]
From README：https://github.com/Tencent/libpag
<img width="837" alt="image" src="https://user-images.githubusercontent.com/16609221/233564502-02931d44-e7d2-4d70-872d-3a9211c35f97.png">

**Comment by peerless2012** [comment]
I see, thanks a lot.
